spring:
  application:
    name: messenger
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

aws:
  s3:
    bucket:
  credentials:
    access-key:
    secret-key:
  region: eu-north-1